<a href="https://colab.research.google.com/github/kash2023k/Pytorch-Project1/blob/main/Pytorch_Project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSORS**

* A torch. Tensor is a multi-dimensional matrix containing elements of a single data type.

* Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

* Default data type of float32.

* More suitable for deep learning than a numpy array.

In [5]:
import torch
import numpy as np

**LISTS**

In [3]:
# List that contains single dimensional and multidimensional array
my_list_single = [1,2,3,4]
my_list_multi = [[1,2,3,4],[5,6,7,8]]
print (my_list_single)
print (my_list_multi)

[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]]


**Numpy Arrays**

In [7]:
np1 = np.random.rand(3,4)
np1

array([[0.75428254, 0.47444137, 0.55710854, 0.10211186],
       [0.32946136, 0.22305164, 0.05077569, 0.45864487],
       [0.73199698, 0.20855019, 0.871003  , 0.96337994]])

In [9]:
np1.dtype

dtype('float64')

**TENSORS**

In [14]:
# Tensor 2D
from numpy._core.numeric import tensordot
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [16]:
# Tensor 3D
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[ 0.6768, -0.1352, -0.8166,  0.9050],
         [ 0.1248, -0.0920, -0.0435, -0.4004],
         [ 0.8191,  1.6814, -1.3336,  0.8878]],

        [[-0.1252, -0.5306, -0.2508,  0.6891],
         [-0.0031,  0.2334, -0.0869, -0.0643],
         [ 0.6331,  0.6875,  0.5057, -0.0903]]])

In [17]:
# Converting the previous Numpy array to Tensor

tensor_conv = torch.tensor(np1)
tensor_conv

tensor([[0.7543, 0.4744, 0.5571, 0.1021],
        [0.3295, 0.2231, 0.0508, 0.4586],
        [0.7320, 0.2086, 0.8710, 0.9634]], dtype=torch.float64)