<a href="https://colab.research.google.com/github/kash2023k/Pytorch-Project1/blob/main/Pytorch_Project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSORS**

* A torch. Tensor is a multi-dimensional matrix containing elements of a single data type.

* Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

* Default data type of float32.

* More suitable for deep learning than a numpy array.

In [2]:
import torch
import numpy as np

**LISTS**

In [3]:
# List that contains single dimensional and multidimensional array
my_list_single = [1,2,3,4]
my_list_multi = [[1,2,3,4],[5,6,7,8]]
print (my_list_single)
print (my_list_multi)

[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]]


**Numpy Arrays**

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.69065022, 0.31954346, 0.45307183, 0.15815666],
       [0.58042404, 0.22408249, 0.43266528, 0.85274258],
       [0.53817194, 0.35323371, 0.67951672, 0.8609025 ]])

In [5]:
np1.dtype

dtype('float64')

**TENSORS**

In [6]:
# Tensor 2D
from numpy._core.numeric import tensordot
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [7]:
# Tensor 3D
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[ 0.1668, -0.7135,  0.6249, -0.3545],
         [-1.1442, -1.2914, -0.5467,  0.4976],
         [ 1.1066,  0.0612, -3.5375, -1.0607]],

        [[ 0.5768,  2.1210,  0.3272, -0.0713],
         [ 1.5143,  1.3372,  1.4981,  1.3060],
         [ 1.3516,  1.1203,  0.1501, -1.2579]]])

In [8]:
# Converting the previous Numpy array to Tensor

tensor_conv = torch.tensor(np1)
tensor_conv

tensor([[0.6907, 0.3195, 0.4531, 0.1582],
        [0.5804, 0.2241, 0.4327, 0.8527],
        [0.5382, 0.3532, 0.6795, 0.8609]], dtype=torch.float64)

**TENSOR OPERATIONS**

In [9]:
mytorch = torch.arange(10)
mytorch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Reshape the data - Reshape and View
mytorch = mytorch.reshape(2,5)
mytorch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
# Reshape if you dont know the number of items with -1
mytorch2 = torch.arange(10)
mytorch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# Using reshape
mytorch2 = mytorch2.reshape(2,-1)
mytorch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
# Using View
mytorch3 = torch.arange(10)
mytorch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
mytorch4 = mytorch3.view(2,5)
mytorch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
# The tensor changes when reshaped with reshape and view

mytorch3[2] = 100
mytorch3
mytorch4

tensor([[  0,   1, 100,   3,   4],
        [  5,   6,   7,   8,   9]])

In [16]:
# Slices allows you to grab a section of the tensor
mytorch5 = torch.arange(10)
mytorch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Grab a specific item
mytorch5[7]

tensor(7)

In [18]:
# Grab a slice
mytorch5[2:7]

tensor([2, 3, 4, 5, 6])

In [19]:
mytorch6 = mytorch5.reshape(5,2)
mytorch6

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [20]:
# Grabbing a second column
mytorch6[:,1] # : denotes from start and 1 denotes the column 2

tensor([1, 3, 5, 7, 9])

In [21]:
# Returning a column keeping the shape
mytorch6[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

**TENSOR MATH OPERATIONS**

*   Add , Subtract , Multiply , Divide , Remainders , Exponents
*   Short hand and Long Hand
* Reassignment



In [22]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [24]:
# Addition Short Hand

tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [25]:
# Addition Long Hand

torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])