<a href="https://colab.research.google.com/github/kash2023k/Pytorch-Project1/blob/main/Pytorch_Project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSORS**

* A torch. Tensor is a multi-dimensional matrix containing elements of a single data type.

* Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

* Default data type of float32.

* More suitable for deep learning than a numpy array.

In [29]:
import torch
import numpy as np

**LISTS**

In [30]:
# List that contains single dimensional and multidimensional array
my_list_single = [1,2,3,4]
my_list_multi = [[1,2,3,4],[5,6,7,8]]
print (my_list_single)
print (my_list_multi)

[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]]


**Numpy Arrays**

In [31]:
np1 = np.random.rand(3,4)
np1

array([[0.15773061, 0.13346601, 0.02171005, 0.84273738],
       [0.95941447, 0.29215464, 0.7470457 , 0.33532329],
       [0.44727738, 0.50225139, 0.04432096, 0.92466979]])

In [32]:
np1.dtype

dtype('float64')

**TENSORS**

In [33]:
# Tensor 2D
from numpy._core.numeric import tensordot
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [34]:
# Tensor 3D
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[ 0.8113, -1.8291,  2.5263, -0.7416],
         [-0.3941,  0.2624, -0.3198,  0.5833],
         [ 0.3882,  0.0511, -1.5100,  1.0917]],

        [[-0.0670,  0.6755,  1.7273,  0.2715],
         [ 1.5933,  1.2310,  0.5332, -1.0224],
         [ 0.2158, -0.8308,  0.4740, -0.0125]]])

In [35]:
# Converting the previous Numpy array to Tensor

tensor_conv = torch.tensor(np1)
tensor_conv

tensor([[0.1577, 0.1335, 0.0217, 0.8427],
        [0.9594, 0.2922, 0.7470, 0.3353],
        [0.4473, 0.5023, 0.0443, 0.9247]], dtype=torch.float64)

**TENSOR OPERATIONS**

In [36]:
mytorch = torch.arange(10)
mytorch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
# Reshape the data - Reshape and View
mytorch = mytorch.reshape(2,5)
mytorch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [38]:
# Reshape if you dont know the number of items with -1
mytorch2 = torch.arange(10)
mytorch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
# Using reshape
mytorch2 = mytorch2.reshape(2,-1)
mytorch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [40]:
# Using View
mytorch3 = torch.arange(10)
mytorch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
mytorch4 = mytorch3.view(2,5)
mytorch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [42]:
# The tensor changes when reshaped with reshape and view

mytorch3[2] = 100
mytorch3
mytorch4

tensor([[  0,   1, 100,   3,   4],
        [  5,   6,   7,   8,   9]])

In [43]:
# Slices allows you to grab a section of the tensor
mytorch5 = torch.arange(10)
mytorch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
# Grab a specific item
mytorch5[7]

tensor(7)

In [45]:
# Grab a slice
mytorch5[2:7]

tensor([2, 3, 4, 5, 6])

In [47]:
mytorch6 = mytorch5.reshape(5,2)
mytorch6

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [48]:
# Grabbing a second column
mytorch6[:,1] # : denotes from start and 1 denotes the column 2

tensor([1, 3, 5, 7, 9])

In [49]:
# Returning a column keeping the shape
mytorch6[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])